name: Java TestNG Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        working-directory: RestAPI   # where pom.xml is
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Upload TestNG Report
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: RestAPI/target/surefire-reports/
